### ISSUE TITLE
Dataset issue 

### ISSUE THREAD

**Issue by Yuiry-IV** [jy6zheng/FacialExpressionRecognition#1]
Hello Joyce, 

This just for your information, but looks like you have an issue in provide notebook with data-set in Process Data section: 
![image](https://user-images.githubusercontent.com/9569717/91311101-fba04100-e7b2-11ea-9675-8d48230e40b5.png)
https://github.com/jy6zheng/FacialExpressionRecognition/blob/master/Facial_recognition.ipynb

Best regards,
Yuriy.

**Comment by jy6zheng** [comment]
@Yuiry-IV  Hey Yuiry, that's because for demonstration when I was running the code, I already unzipped the file. Normally, the file just needs to be in the specified directory. Thanks for bringing it up :)
